### ISSUE TITLE
Preserve usage metrics

### ISSUE THREAD

**Issue by csgillespie** [jumpingrivers/audit.connect#2]
Connect records usage metrics about features that have been used by clients. It would be great to preserve this information. There is no public API but the database could be modified directly.

1. The data is actually a timestamp, is this first use or last use? If first use we can easily revert any metrics falsely triggered by the UAT.
2. We would need direct database access, so only on systems that we manage.

@csgillespie for discussion

Read-only API: https://rsc.jumpingrivers.cloud/__api__/v1/experimental/feature_usage/

Summary in admin interface: https://rsc.jumpingrivers.cloud/connect/#/admin/metrics

Sample output:

```yaml
connect_version: 2023.03.0
date_time: 2023/05/16 14:02:53.111
custom_email: false
interactive_quarto: false
interactive_rmarkdown: false
jupyter_notebook: true
jupyter_voila: false
open_solo: true
parameterized_quarto: false
parameterized_rmarkdown: true
parameterized_rmarkdown_variants: false
plumber: true
python_api: true
python_bokeh: false
python_dash: false
python_shiny: false
python_streamlit: true
quarto: true
rmarkdown: true
scheduled: true
shiny: true
static: true
static_pin: true
vanity_url: true
```
